### ISSUE TITLE
FYI about random access on the web

### ISSUE THREAD

**Issue by TomasHubelbauer** [greggman/unzipit#1]
> Unfortunately AFAIK there are no web standards for remote random access file reading (WEBDAV?) so whatever proprietary protocol you use you'd have to adapt on your own.

I would like to highlight that it is possible to do random access on the web if a server supports HTTP range headers. There even were ZIP-reading demos in JS which relied on it - do a HEAD request to find out the total size, read the central directory at the end of the file first (some guesswork involved, basically read some-buffer-sized chunks from the end until you have the whole directory) and list the archive, allowing decompression on-demand by making a range request for the compressed data.

I don't have any links handy, not that it matters, just wanted to let you know this in case you weren't aware of it.

Also, this might be interesting to you as well: GitHub Pages support HTTP range headers, I've implemented a fetch demo here which makes use of that fact:

https://github.com/TomasHubelbauer/fetch-range-request

**Comment by greggman** [comment]
cool! thanks. I'll take a look

**Comment by TomasHubelbauer** [comment]
This is kinda random, but I just so happened to need exactly what I described above: to be able to extract files on-demand from a large archive without having to download the entire archive and I've built a demo showing how to do it. You can check it out here if you are still interested in looking into range requests:

https://tomashubelbauer.github.io/fatcow-icons/wip

The code:

https://github.com/TomasHubelbauer/fatcow-icons/tree/master/wip

Just thought I'd drop by and say this because I remembered I talked about this in some issue and miraculously I managed to find which one, too!

**Comment by greggman** [comment]
I don't know if you saw but based on your original comment I wrote this

https://github.com/greggman/unzipit#streaming

**Comment by TomasHubelbauer** [comment]
I didn't, thanks for letting me know! 🙂
