### ISSUE TITLE
Chrome 100% CPU when calling blob on encrypted zip file

### ISSUE THREAD

**Issue by Najji** [greggman/unzipit#12]
Hey,

I have a zip file (attached) which I encrypted in my mac (using `zip -er`). Calling `blob` on the entry causes it to crash chrome. 

There is also another encrypted zip file I have (not attached, had trouble re-creating the zip file I could upload to a public place), where if I call `blob` on an entry it throws `Uncaught (in promise) TypeError: Cannot read property '0' of undefined unzipit.module.js:151`. This results in the exception escaping my try...catch, I think it needs to be caught in the library and be rethrown. Happy to create a separate issue if needed for this one though if you prefer.

Interestingly, both were encrypted in similar ways, just failing in different parts. Maybe the algorithm being applied to the encrypted data just makes it blow up?

[ziptest.zip](https://github.com/greggman/unzipit/files/4894691/ziptest.zip)
Password is test

Let me know if you need any more information.

**Comment by greggman** [comment]
thanks for the repo. I'm not sure what to do at the moment other then reject the file as encrypted. I have/had no plans to support encrypted zip files.

As for crashing that's like that it ran out of memory. I can think of 2 things to prevent that.

1. On the user's side check `entry.size` before asking for the data. If it's larger than you support give the user an error (file too large).  Obviously the library itself has no idea what "too large" is.

2. Internally I can consider adding a check that the decompressed size is never larger than `entry.size`.

**Comment by Najji** [comment]
Hey,

Would it be trivial to find out if a file is encrypted? I believe you may need to check the compression method/ potentially extra fields? I do like the idea of rejecting files when reading an entry (when `blob` is called) but seems like reading the central directory is fine

When it crashes I don't think it's because an entry is too large, the zip I uploaded has a very small entry on which it crashes.

**Comment by greggman** [comment]
So I added `entry.encrypted` if the entry is encrypted. If you try to call any of the functions to get data from an encrypted entry they will throw.
