### ISSUE TITLE
Ummm

### ISSUE THREAD

**Issue by mrjjwright** [greggman/unzipit#2]
🔥, you just crushed my use case, thank you!

**Comment by greggman** [comment]
Um, are you saying I solved a problem for your or broke something? Hoping it was solved instead of broke 😅

**Comment by mrjjwright** [comment]
Solved, haha!

**Comment by mrjjwright** [comment]
Your lib is working so well and fast and when I get some time I am going to micro profile it up against: https://github.com/nika-begiashvili/libarchivejs .

**Comment by greggman** [comment]
Lol, ... If I had seen that library I might not have written this one. It looks like it does what I needed 😅

I can't take credit for the speed though. That's from [this lib](https://github.com/photopea/UZIP.js)
