### ISSUE TITLE
Workers in the browser

### ISSUE THREAD

**Issue by valentinoli** [greggman/unzipit#21]
Currently, this module only supports workers in Node.js
Would it be difficult to add support for unzipping in parallel with Web Workers in the browser?

**Comment by greggman** [comment]
it works just fine in web workers. See example in the repo.

**Comment by valentinoli** [comment]
I tried but it relies on a Node module [`worker_threads`](https://github.com/greggman/unzipit/blob/580c5cd75ca136fd918ae173f422600fa35c57a4/src/inflate-worker.js#L14)

**Comment by valentinoli** [comment]
Moreover, the example is titled "[Workers in Node](https://github.com/greggman/unzipit#workers-in-node)"

**Comment by greggman** [comment]
https://github.com/greggman/unzipit#with-workers

**Comment by valentinoli** [comment]
Ah, I was getting a webpack error:

```
This dependency was not found:      
* worker_threads in ./node_modules/unzipit/dist/unzipit-worker.module.js       
To install it, you can run: npm install --save worker_threads
```

Solved it by using the webpack file-loader

```js
{
  test: /unzipit-worker.module.js$/,
  use: [
    {
      loader: 'file-loader',
      options: {
        name: '[path][name].[contenthash:7].[ext]'
      }
    }
  ]
}
```

Thanks!
