### ISSUE TITLE
Typescript type error when using HTTPRangeReader

### ISSUE THREAD

**Issue by t123yh** [greggman/unzipit#30]
```typescript
const reader = new HTTPRangeReader(textFieldRef.current.value);
const { entries } = await unzip(reader);
```

Got error: `Argument of type 'HTTPRangeReader' is not assignable to parameter of type 'string | ArrayBuffer | TypedArray | Blob | Reader'.`

It seems that in https://github.com/greggman/unzipit/blob/master/dist/unzipit.d.ts , `HTTPRangeReader` is not classified as a `Reader`.

**Comment by greggman** [comment]
Can you test just patch your local `unzipit.d.ts` by adding `implements Reader` to `HTTPRangeReader`?

If that's all that's needed I'll add it

In particular I want to know I need to add more than that. Thanks!

```ts
export class HTTPRangeReader implements Reader {
	constructor(url: string);
}
```

**Comment by t123yh** [comment]
Only adding `implements` does not seem to work. I think we have to add members from `Reader` interface:

```typescript
export class HTTPRangeReader implements Reader {
  constructor(url: string);
  getLength(): Promise<number>;
  read(offset: number, size: number): Promise<Uint8Array>;
}
```

**Comment by greggman** [comment]
Thanks!

https://github.com/greggman/unzipit/commit/6181c0c44e6a7a908e5d0efb7db7b2773d3dff4e
