### ISSUE TITLE
Migrating from 0.0.4 to 0.1.0

### ISSUE THREAD

**Issue by greggman** [greggman/unzipit#6]
Made some major changes between 0.0.4 and 0.1.0

* There are now 3 functions exported

    ```js
    // 0.0.4
    import unzipit from 'unzipit';
    ```

    ```js
    // 0.1.0
    import { unzip, unzipRaw, setOptions } from `unzipit`;
    ```

    Or if you prefer

    ```js
     import * as  unzipit from `unzipit`;

    // now you can call `unzipit.unzip`, `unzipit.unzipRaw` and `unzipit.setOptions`
    ```

* `unzip` now returns an object of names to entries

    ```
    // 0.0.4
       const entries = await unzipit(url);  // entries was an array
       const data = await entries[3].arrayBuffer();
   ```

    ```
    // 0.1.0
       const entries = await unzip(url);  // entries is an object
       const data = await entries['some/file/path/name'].arrayBuffer();
   ```

    If you want/need an array call `unzipRaw`. You'd only need an array
    if you want to handle non-utf8 filenames.

* It now supports inflating using 1 or more workers.

    To use workers you need to call `setOptions` and pass in the url of the worker module

    ```js
    import * as unzipit from 'unzipit';
    unzipit.setOptions(workerURL: 'path/to/unzipit-worker.module.js');
    ```

    It's not at all clear to me how to automate that with the various builders (browserify, webpack, rollup, etc...) If you know of an example please comment.

See README for more

**Comment by mrjjwright** [comment]
I had just started working on the names to entries fix so this is really nice.

**Comment by mrjjwright** [comment]
inflate workers....🔥🔥🔥
