### ISSUE TITLE
Nested ZIP archives

### ISSUE THREAD

**Issue by NathanJCleaver** [greggman/unzipit#7]
First let me say what a fantastic library. It matches our use case perfectly.
We are wondering how to go about handling nested archives with range requests; that is zip archives inside the top-level zip archive. 

From the top-level archive we have a Blob url which is the nested archive. Is there any way to `unzip()` this?

**Comment by greggman** [comment]
If it's a blob can't you just pass it to unzipit again?

```
const {topEntries} = await unzipit(urlToFileWithNestedZips);
const blob = await topEntries['nested.zip'].blob();
const {innerEntries} = await unzipit(blob);
```

???

**Comment by NathanJCleaver** [comment]
Yes, but does this use HTTP range requests? It looks like no, because we do not pass an HTTP Range Reader to unzip, and can't because the blob URL can't be used to create the reader. So we are using range requests on the outer zip archive but have to retrieve entire nested archives.

**Comment by greggman** [comment]
You can retrieve the inner zip with range requests. There's no way to know the actual offsets without decompessing the entire file.

Let's say you look at the outer zip and see

````
1111111122222222CD
```

So the central directory at the end says zip 1 starts at 0 and ends at 7 and zip 2 starts at 8 and ends at 16. Now you want to load 2 but 2 is compressed. 

Compressed it looks like 

````
CCCCCCCC
````

decompressed it looks like

```
444455556666CD
```

3 files, 4 long each with centeral dir (CD) at end. But you can't even read the CD without first decompressing can you can't decompress just the CD, the entire file until decompressed is just one blob of effectively encrpyted data.

**Comment by NathanJCleaver** [comment]
Thanks for the explanation.
